// "use client";

import { SessionProvider } from "next-auth/react";
import Footer from "../components/footer";
import Navigation from "../components/navigation";
import "../styles/global.css";
import { AuthProvider } from "./util/AuthContext";
import "react-quill/dist/quill.snow.css";

export const metadata = {
  title: "Home",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <SessionProvider> */}
        <AuthProvider>
          <Navigation />
          <div id="wrap">{children}</div>
          <Footer />
        </AuthProvider>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
